lib/closure_tree/model.rb

reversing array of strings is faster than reversing array of ActiveRecord models

faster ancestry_path method

---

README.md

I changed a link called `#sort_order` to `#deterministic-ordering` as there was no `#sort_order` anchor in the README

Fixed a anchor link for in the README

---

lib/closure_tree/digraphs.rb
spec/tag_examples.rb

Fix issues with UUID and the `.dot` files.
I kept getting errors like this:
```
Warning: syntax ambiguity - badly delimited number '-16289e' in line 17 of example.dot splits into two tokens
Warning: syntax ambiguity - badly delimited number '-2e' in line 18 of example.dot splits into two tokens
Warning: syntax ambiguity - badly delimited number '-4a' in line 18 of example.dot splits into two tokens
Warning: syntax ambiguity - badly delimited number '-16289e' in line 18 of example.dot splits into two tokens
Warning: syntax ambiguity - badly delimited number '43c' in line 19 of example.dot splits into two tokens
Warning: syntax ambiguity - badly delimited number '-20c' in line 19 of example.dot splits into two tokens
Warning: syntax ambiguity - badly delimited number '-42e' in line 19 of …
```

fix uuids for graphviz

---

spec/db/schema.rb
spec/generators/migration_generator_spec.rb
spec/label_spec.rb

Fix Rails 5 deprecation warning for not explicitly setting the null option
for timestamps. Also moved other timestamps to use timestamps method.
This PR also changes passing id into `exists?`
This deprecation warning was introduced in https://github.com/rails/rails/pull/16481

Specify null false for timestamps and pass id to exists?

---

spec/tag_examples.rb

I ran into the issue that has occurred for multiple programmers.
Issues:
~~#37~~ (Different issue: this is `.hash_tree` from a non-tree relation)
~~#76~~ (Different issue: this was fixed many versions ago, and has test coverage)
~~#28~~ (Different issue: this was fixed many versions ago, and has test coverage) 
The issue is occurring because the call to hash_tree is on an already-scoped ActiveRecord relation, and your previous tests only cover Class.hash_tree.
example:
```ruby
d = Tag.find_or_create_by_path %w[a b c d]
h = Tag.find_or_create_by_path %w[e f g h]
Tag.first.children.hash_tree
NoMethodError - undefined method `[]=' for nil:NilClass:
(gem) closure_tree-5.1.1/lib/closure_tree/hash_tree.rb:52:in `block in build_hash_tree'
(gem) …
```

New multi-trees test, failing

---

lib/closure_tree/hierarchy_maintenance.rb

```
QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Delete on log_hierarchies  (cost=4403.03..6923802.33 rows=169553156 width=6) (actual time=52728.567..52728.567 rows=0 loops=1)
->  Seq Scan on log_hierarchies  (cost=4403.03..6923802.33 rows=169553156 width=6) (actual time=52728.564..52728.564 rows=0 loops=1)
Filter: ((hashed SubPlan 1) OR (descendant_id = 1022566))
Rows Removed by Filter: 338996939
SubPlan 1
->  Unique  (cost=0.57..4403.03 rows=1 width=4) (actual time=0.085..0.085 rows=0 loops=1)
->  Index Only Scan using log_anc_desc_idx on log_hierarchies log_hierarchies_1  (cost=0.57..4396.98 rows=2420 width=4) (actual time=0.085..0.085 rows=0 …
```

Improve performance issue for DELETE command

---

lib/closure_tree/finders.rb

Rails 5 introduces a #without() method and it is used instead of the one defined in the ClassMethods module. This caused #ancestors() to return an Array rather than a relation object.

Fixed Rails 5 Active Record method name collision.

---

lib/closure_tree/hierarchy_maintenance.rb

This instance variable was introduced [here](https://github.com/mceachen/closure_tree/commit/31de226bc774ee37a9309fdcf84d6417cb5e87f6) but doesn't seem to be used anymore.

Remove unused instance variable

---

CHANGELOG.md
README.md
lib/closure_tree.rb
lib/closure_tree/configuration.rb
lib/closure_tree/has_closure_tree.rb
lib/generators/closure_tree/config_generator.rb
lib/generators/closure_tree/templates/config.rb

Class `has_closure_tree.rb` was validating only the Heroku config unfortunately other PaaS like Catalyze does not have the same configuration, after this PR will be posible create a config file and skip the error when app is deployed for one of those platforms.

Check db connection

---

lib/closure_tree/model.rb
lib/closure_tree/support.rb

ActiveRecord 5 now defaults a `belongs_to` relation to be required, which does not work for a tree structure where the root will not have a `:parent`.
To manage this change in default behavior, AR 5 adds an `optional: true` key, which I have added here. However, this key is not allowed in versions prior to AR 5 and will raise an exception if provided, so its inclusion requires a conditional check to maintain backwards compatibility.
Per earlier comments in #196, I've added a method to the `support.rb` file that checks the version and strips the `optional` key if necessary.  I've tried to be consistent with the naming of the support method, but am happy to make changes if we'd rather do something different.  (Not sure if the name is acceptable, or if you like the use of a ternary …

adds ActiveRecord >= 5.0.0.beta1 support for tree roots; fixes #195

---

lib/closure_tree.rb
lib/closure_tree/has_closure_tree_root.rb
spec/db/models.rb
spec/db/schema.rb
spec/has_closure_tree_root_spec.rb
spec/support/exceed_query_limit.rb
spec/support/query_counter.rb

So many times in working with trees I have a model, say Group, that has an associated tree, say of Users (say, with parent/child relationship defined by referral, as in the closure_tree specs). I keep a reference to the root of the tree, and would like to be able to load the root and all its descendants. I know that self_and_descendants can do this, but I want two things in addition:
1. I don't want an array of nodes--I still want to be able to traverse the eager-loaded nodes using the familar `.parent` and `.children` methods. This is the way you're supposed to traverse a tree and this is how tree recursion typically and elegantly works.
1. I still want to be able to eager load associations of the User class.
Unless I'm missing something, there is no way to do this currently. …

has_closure_tree_root - Better tree eager loading

---

.travis.yml
lib/closure_tree/finders.rb
lib/closure_tree/numeric_deterministic_ordering.rb

The code contains several statements like "GROUP BY 1". This is not supported in MS SQL, but can easily rewritten to "GROUP BY ascendent_id", which works for all SQL implementations.

Enhance compatibility for SqlServer 2008

---

README.md
lib/closure_tree/has_closure_tree_root.rb
spec/db/schema.rb
spec/has_closure_tree_root_spec.rb

Try this on for size. I also added some generic notes about eager loading since the topic is not currently mentioned in the docs.

Added documentation for has_closure_tree_root

---

lib/closure_tree/hierarchy_maintenance.rb

I'm migrating from system where my model already has a`parent_id` column so following the documentation when I tried running `Tag.rebuild!` to have my `tag_hierarchies` table truncated and rebuilt I got an error. 
Initially this resulted in `Java::JavaLang::OutOfMemoryError: GC overhead limit exceeded` (with the default JVM heap size of 512MB). 
Expanding the memory via `JRUBY_OPTS=-J-Xmx32G` did the trick and `rebuild!` passed successfully but with ever expanding heap.
You can take a look of this `jvisualvm` screenshots made before the proposed change:
and after:
This even allows my 512MB setup to succeed:
- My test database is populated with ~49k nodes that results in ~240k rows hierarchy and is roughly 10 times smaller than production.
- The setup:
- macOS Sierra 10.12.3, 3.5 GHz Intel …

Use batch processing methods in Hierarchy Maintenance when looping through database records

---

lib/closure_tree/has_closure_tree.rb
lib/closure_tree/has_closure_tree_root.rb
spec/pool_spec.rb

When application code being loaded `has_closure_tree` method will get database connection implicitly and will not return it into the pool.
In some circumstances this connection will not be available for request processing at runtime anymore.
In my case I've launched Rails app in Puma application server with one thread and with DB pool size set to one and I was unable to do any requests as only available connection was taken by closure_tree gem (I always get `ActiveRecord::ConnectionTimeoutError`)

Return database connection into pool after configuration

---

lib/closure_tree/hierarchy_maintenance.rb
lib/closure_tree/numeric_deterministic_ordering.rb

Notably, there are still 4 test failures on ActiveRecord-edge, having to do with the "chained activerecord association subroot" tests. Debugging those is beyond my level of acquaintance with the code base. But the deprecation warnings surrounding `attribute_changed?`, `attribute_was`, and `changes` have all been silenced here.

Fix ActiveSupport 5.1 deprecation warnings

---

README.md

Maybe it could be part of the template generation.
This pull request avoid the user search into the code to know the I18n key.

Add custom I18n example on doc

---

lib/closure_tree/numeric_order_support.rb

The change simply exempts all records that will not change in the update.
Since `reorder_with_parent_id` is called a lot for rebuild! this leads to a huge performance boost for our data.
(many small trees, we have some 10k records and 4k top level elements)
Great tests by the way. My first solution got the check wrong with respect to null values (`!=` instead of `is distinct from`)...
I ran the tests for postgres only and one rails version, but the nature of the change should allow that.

speed up rebuild in postgres

---

spec/db/schema.rb

This should get tests passing again!

Update schema for Rails 5.1 support

---

README.md

Description on how to work around STI subclasses remove other subclasses hierarchies when calling Subclass.rebuild! method.

Update README with STI rebuild! behavior

---

lib/closure_tree/finders.rb
spec/tag_examples.rb

Previously `Tag.find_by_tree([])` would return essentially `Tag.first`.
This was confusing as I expected it this should return `nil`.
I've also added a number of similar specs of passing all the blank values I can think of
as `Tag.find_by_tree` didn't seem to already be tested with these various blank values.

Fix `tree.find_by_tree([])`

---

closure_tree.gemspec
lib/generators/closure_tree/migration_generator.rb
lib/generators/closure_tree/templates/create_hierarchies_table.rb.erb
spec/generators/migration_generator_spec.rb

Rails 5.x expects migrations to subclass `ActiveRecord::Migration[5.x]`

fixed generator specs and added migration version

---

lib/closure_tree/model.rb
lib/closure_tree/numeric_deterministic_ordering.rb

Starting from Rails 5.2 passing raw SQL to methods like `order` is deprecated and in 6.0 it will be forbidden because of security concerns.
When users sure that passed string is safe, they must wrap it with `Arel.sql`.

Eliminate deprecation warnings in ActiveRecord 5.2

---

lib/closure_tree/finders.rb
lib/closure_tree/hash_tree_support.rb
lib/closure_tree/hierarchy_maintenance.rb
lib/closure_tree/numeric_deterministic_ordering.rb
lib/closure_tree/support_attributes.rb

When used on table name alias, Oracle Database don't support used 'AS'.

When using 'oracle_enhanced', remove 'AS' on the table_name alias.

---

README.md
lib/closure_tree/model.rb
spec/label_spec.rb

Added methods parent_of?, root_of?, ancestor_of?, descendant_of?, child_of? for checking relationship between nodes

Added instance methods to determine the relationship between 2 nodes

---

README.md
lib/closure_tree/has_closure_tree.rb
lib/closure_tree/has_closure_tree_root.rb
lib/closure_tree/numeric_deterministic_ordering.rb
lib/closure_tree/numeric_order_support.rb
lib/closure_tree/support_attributes.rb
spec/db/models.rb
spec/label_spec.rb

From the proposed Readme text:
By default, root nodes are also assigned order values globally across the whole database table. So for instance if you have 5 nodes with no parent, they will be ordered 0 through 4 by default. If your model represents many separate trees and you have a lot of records, this can cause performance problems, and doesn't really make much sense.
This PR adds an option for disabling this behavior.
This was proposed in issue #282.

Added dont_order_roots option

---

README.md
lib/closure_tree/model.rb
spec/label_spec.rb

Add `#family_of?` which returns true if current node and another one have a same root.

Add an instance method to check the relationship between 2 nodes: #family_of?

---

lib/closure_tree/has_closure_tree_root.rb

These restrictions make sense for `has_closure_tree` because it's a fully custom method, whereas `has_closure_tree_root` is a wrapper around `has_one`. Rather than list out all the possible keys that `has_one` can accept, I think we should just remove the restriction. Thoughts?

Remove options restrictions on has_closure_tree_root

---

lib/closure_tree/hierarchy_maintenance.rb

Fix warnings for uninitialized variables `@was_new_record` and `@_ct_skip_cycle_detection `

Fix uninitialized variable warnings

---

lib/closure_tree/support.rb
lib/closure_tree/support_attributes.rb

1. Unused variable warning in `support.rb` - due to using a `class_eval` string vs a `class_eval` proc.  
2. Unused variable warning in `support_attributes.rb` - not sure what original intention was here - perhaps was to make `nulls_last_order_by` accept reverse, or to use keyword arguments in `order_by_order`

Fix unused variable warnings

---

README.md

It links to an issue closed two days ago. No longer needed?

Remove 'vote on future' link from README.md

---

lib/closure_tree/hash_tree_support.rb

Fix warning for alignment of end with def

---

README.md

The [CHANGELOG states](https://github.com/ClosureTree/closure_tree/blob/master/CHANGELOG.md#700) that version 7.0.0 is tested against Rails 5.2, so this should be added to the README.

Update README with Rails 5.2 information

---

gemfiles/activerecord_4.2.gemfile
gemfiles/activerecord_5.0.gemfile
lib/closure_tree.rb

This is needed for Rails 6+ as this core_ext is no longer indirectly loaded.
It would be nice to use
```
<<~HEREDOC
this will lose indentation
HEREDOC
```
introduced in Ruby 2.3 but this would break backwards compatibility.

Directly require core_ext for String#strip_heredoc

---

lib/closure_tree/support.rb

Solves Rails 6 deprecation warning.
Opening a duplicate PR as https://github.com/ClosureTree/closure_tree/pull/349 seems stale.
Fixes https://github.com/ClosureTree/closure_tree/issues/346.

Call Module#module_parent instead of deprecated #parent

---

lib/closure_tree.rb
lib/closure_tree/finders.rb
lib/closure_tree/hash_tree_support.rb
lib/closure_tree/hierarchy_maintenance.rb
lib/closure_tree/numeric_deterministic_ordering.rb
lib/closure_tree/numeric_order_support.rb

Switching to squish keeps log output on a single line.
Before:
```
Page Load (2.7ms)  SELECT "pages".* FROM "pages" INNER JOIN (
SELECT descendant_id, MAX(generations) as depth
FROM "page_hierarchies"
GROUP BY descendant_id
) AS generation_depth
ON "pages".id = generation_depth.descendant_id ORDER BY generation_depth.depth, position
```
After:
```
Page Load (1.9ms)  SELECT "pages".* FROM "pages" INNER JOIN ( SELECT descendant_id, MAX(generations) as depth FROM "page_hierarchies" GROUP BY descendant_id ) AS generation_depth ON "pages".id = generation_depth.descendant_id ORDER BY generation_depth.depth, position
```

Replace strip_heredoc with squish

---

lib/closure_tree/model.rb
lib/closure_tree/support.rb

This PR intend to fix Ruby 2.7 deprecation warning:
```
closure_tree-7.1.0/lib/closure_tree/model.rb:9: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```
I've updated some method names in order to simplify to reflect the new usage.

Fix kwargs usage for Ruby 2.7

---

lib/closure_tree/support_attributes.rb

Hi!
This PR is only wrapping with Arel.sql a raw SQL argument passed when deterministic ordering is set. 
Rails 6 is showing a deprecation warning and it seem will be already broken by version 6.1
`DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "-\"MODEL\".\"sort_order\" DESC". Non-attribute arguments will be disallowed in Rails 6.1. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql().
`

Fix raw SQL argument deprecation warning

---

lib/closure_tree/support.rb

#382 
FYI: In my case, I have a namespace AAA for billing, and billing model inherits from AAA::ApplicationRecord. 
Like the following code:
```
module AAA
class Billing < ApplicationRecord
connects_to database: { writing: :foo_service, reading: :foo_service}
has_closure_tree
end
end
module AAA
class ApplicationRecord < ActiveRecord::Base
connects_to database: { writing: :aaa, reading: :aaa }
self.abstract_class = true
end
end
```
Therefore if I follow the unmodified code to execute, AAA::BillingHierarchy will inherit from ApplicationRecord, not AAA::ApplicationRecord, then it will connect to primary database, not aaa database. 
PTAL.Thank you.

fix: hierarchy model with namespace should inherit from the superclass of basic model

---

README.md
Rakefile
closure_tree.gemspec
spec/closure_tree/model_spec.rb
test/closure_tree/model_test.rb
test/test_helper.rb

Migrate to minitest

---

CHANGELOG.md
lib/closure_tree/model.rb

This is helpful because we can more easily eager load ancestor_hierarchies than we can ancestors to avoid n + 1 queries.
```ruby
tag = Tag.includes(:ancestor_hierarchies).first
tag.depth
```

Reference ancestor_hierarchies in depth instead of ancestors

---

spec/support/schema.rb
test/closure_tree/tag_test.rb
test/closure_tree/uuid_tag_test.rb
test/test_helper.rb

While trying to run the tests locally, I had to make a few changes to make things work:
- `MiniTest` has apparently been renamed to `Minitest` at some point (this apparently also broke the most recent [CI runs](https://github.com/ClosureTree/closure_tree/actions/runs/6684636015/job/18162114666))
- Schema files have to use `force: :cascade` so the recreation of the schema does not fail because of dependencies (at least on PostgreSQL)
- the `tag_examples` module was evaluated as actual tests while trying to run any different test file, leading to hundreds of errors. Just requiring it where it's needed seems to help with that.
Now I am at the point where all tests except the parallel_test are running fine, but that's a separate topic :)

Test fixes

---

lib/closure_tree/digraphs.rb
lib/closure_tree/finders.rb
lib/closure_tree/hash_tree.rb
lib/closure_tree/hierarchy_maintenance.rb
lib/closure_tree/numeric_deterministic_ordering.rb

change 
`module ClassMethods`
to 
`class_methods do`

feat: use new concerns syntax

---

lib/closure_tree/active_record_support.rb
lib/closure_tree/support.rb
spec/spec_helper.rb
spec/support/schema.rb

feat: remove unused code

---

spec/support/models.rb

This PR is to prepare for the  multi db support.

test: inherit models from ApplicationRecord

---

Appraisals
gemfiles/activerecord_6.1.gemfile
gemfiles/activerecord_7.0.gemfile
gemfiles/activerecord_7.1.gemfile

While execute spec with appraisal, I caught error.
```
An error occurred while loading ./spec/closure_tree/matcher_spec.rb. - Did you mean?
rspec ./spec/closure_tree/has_closure_tree_root_spec.rb
Failure/Error: ActiveRecord::Base.establish_connection
LoadError:
Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-2.0.2-arm64-darwin. Make sure all dependencies are added to Gemfile.
```
sqlite3 v2 is supported by only rails 7.2 or above
ref: https://github.com/rails/rails/commit/fd1c635d2f1

fix sqlite3 version

---

spec/spec_helper.rb
test/test_helper.rb

The `concurrent-ruby` gem stopped depending on Logger. It should be now required manually.

Fix the uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger error

---

Gemfile
closure_tree.gemspec
gemfiles/activerecord_7.1.gemfile
gemfiles/activerecord_7.2.gemfile
gemfiles/activerecord_8.0.gemfile
gemfiles/activerecord_edge.gemfile
lib/closure_tree/numeric_order_support.rb
lib/closure_tree/support.rb
lib/closure_tree/support_flags.rb
test/closure_tree/matcher_test.rb
test/support/tag_examples.rb
test/test_helper.rb

- Removed deprecated Rails 3/4 features
- Removed use_attr_accessible? and include_forbidden_attributes_protection? methods.
- Removed attr_accessible declarations.
- Fixed SQLite compatibility.
- Auto-disabled advisory locks for SQLite (since it doesn't support them) 
- SQLite will be supported if it behave, if causing maintenance burden, we  will remove.
This commit is transitional , further refactoring are required.

feat: use new with_advisory_lock

---

release-please-config.json

This PR updates the release-please configuration to properly recognize the v8.0.0 release and enable it to create release PRs for subsequent commits.
- Add bootstrap-sha pointing to the v8.0.0 release commit
- Add detailed package configuration for better release management
Release-please wasn't creating PRs because it didn't recognize the manually created v8.0.0 release. This configuration tells release-please where to start looking for new commits.
After this is merged, release-please should create a PR for version 8.1.0 including:
- feat: rewrite with clean api (#451)
- refactor: convert SQL queries to Arel where feasible (#453)
- feat: Add runtime advisory lock name customization and multi-database documentation (#454)

fix: configure release-please to recognize v8.0.0 release

---

README.md
lib/closure_tree.rb
lib/closure_tree/association_setup.rb
lib/closure_tree/configuration.rb
lib/closure_tree/has_closure_tree.rb
lib/closure_tree/model.rb

Restores proper deprecation for the `database_less` configuration option that was removed in v9.1.0 without deprecation, causing deployment failures for users who had this configuration in their production setup.
- Created minimal `Configuration` class to handle the deprecated option with proper warnings
- Updated `ClosureTree.configure` to show specific deprecation messages
- Made the option a no-op (always returns false) since it's no longer needed
- Improved HasClosureTree include order dependencies with `AssociationSetup` concern
- Updated conditional `acts_as_tree` alias to prevent conflicts with other gems
- Fixed README code examples formatting
This addresses the breaking change introduced in v9.1.0 where users with existing configuration would see deployment failures. Now they get …

fix: restore proper deprecation for database_less configuration

---

README.md

I had weird issues caused by an enum defined on my model that conflicted with closure_tree. I had a hard time understanding this because [this alias](https://github.com/ClosureTree/closure_tree/blob/99e295a97611759d379c457282336635497d5f4d/lib/closure_tree/model.rb#L44) was not documented in the README.
```rb
class TaxonomyNode < ApplicationRecord
enum :level, { family: 0, subfamily: 1, tribe: 2, genus: 3, subgenus: 4 }, validate: true
has_closure_tree
end
```
This PR adds an mention in the README.
It would also be a good idea to provide a list of potentially conflicting method names.

Document `alias level depth` in README
